'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property PLAYER_ASPECT_RATIO() As Byte
            Get
                Return CType(Me("PLAYER_ASPECT_RATIO"),Byte)
            End Get
            Set
                Me("PLAYER_ASPECT_RATIO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RECENT_PROJECTS() As String
            Get
                Return CType(Me("RECENT_PROJECTS"),String)
            End Get
            Set
                Me("RECENT_PROJECTS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LAST_PROFILE_PATH() As String
            Get
                Return CType(Me("LAST_PROFILE_PATH"),String)
            End Get
            Set
                Me("LAST_PROFILE_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("STANDARD")>  _
        Public Property DEFAULT_PROFILE() As String
            Get
                Return CType(Me("DEFAULT_PROFILE"),String)
            End Get
            Set
                Me("DEFAULT_PROFILE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SMT Phoenix")>  _
        Public Property APPLICATION_NAME() As String
            Get
                Return CType(Me("APPLICATION_NAME"),String)
            End Get
            Set
                Me("APPLICATION_NAME") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LAST_STREAM_PATH() As String
            Get
                Return CType(Me("LAST_STREAM_PATH"),String)
            End Get
            Set
                Me("LAST_STREAM_PATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LAST_PROJECT() As String
            Get
                Return CType(Me("LAST_PROJECT"),String)
            End Get
            Set
                Me("LAST_PROJECT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property PLAYER_REGION() As Byte
            Get
                Return CType(Me("PLAYER_REGION"),Byte)
            End Get
            Set
                Me("PLAYER_REGION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("16")>  _
        Public Property PLAYER_AUDIO_LANG() As Byte
            Get
                Return CType(Me("PLAYER_AUDIO_LANG"),Byte)
            End Get
            Set
                Me("PLAYER_AUDIO_LANG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property PLAYER_AUDIO_LANG_EXT() As Byte
            Get
                Return CType(Me("PLAYER_AUDIO_LANG_EXT"),Byte)
            End Get
            Set
                Me("PLAYER_AUDIO_LANG_EXT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("16")>  _
        Public Property PLAYER_SUB_LANG() As Byte
            Get
                Return CType(Me("PLAYER_SUB_LANG"),Byte)
            End Get
            Set
                Me("PLAYER_SUB_LANG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property PLAYER_SUB_LANG_EXT() As Byte
            Get
                Return CType(Me("PLAYER_SUB_LANG_EXT"),Byte)
            End Get
            Set
                Me("PLAYER_SUB_LANG_EXT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("16")>  _
        Public Property PLAYER_MENU_LANG() As Byte
            Get
                Return CType(Me("PLAYER_MENU_LANG"),Byte)
            End Get
            Set
                Me("PLAYER_MENU_LANG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property PLAYER_PARENTAL_LEVEL() As Byte
            Get
                Return CType(Me("PLAYER_PARENTAL_LEVEL"),Byte)
            End Get
            Set
                Me("PLAYER_PARENTAL_LEVEL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("220")>  _
        Public Property PLAYER_PARENTAL_COUNTRY() As Short
            Get
                Return CType(Me("PLAYER_PARENTAL_COUNTRY"),Short)
            End Get
            Set
                Me("PLAYER_PARENTAL_COUNTRY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UOP_TEMPLATES() As String
            Get
                Return CType(Me("UOP_TEMPLATES"),String)
            End Get
            Set
                Me("UOP_TEMPLATES") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property WINDOW_MAIN_X() As Short
            Get
                Return CType(Me("WINDOW_MAIN_X"),Short)
            End Get
            Set
                Me("WINDOW_MAIN_X") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property WINDOW_MAIN_Y() As String
            Get
                Return CType(Me("WINDOW_MAIN_Y"),String)
            End Get
            Set
                Me("WINDOW_MAIN_Y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property WINDOW_VIEWER_X() As String
            Get
                Return CType(Me("WINDOW_VIEWER_X"),String)
            End Get
            Set
                Me("WINDOW_VIEWER_X") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property WINDOW_VIEWER_Y() As String
            Get
                Return CType(Me("WINDOW_VIEWER_Y"),String)
            End Get
            Set
                Me("WINDOW_VIEWER_Y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property PREFERRED_AV_MODE() As Byte
            Get
                Return CType(Me("PREFERRED_AV_MODE"),Byte)
            End Get
            Set
                Me("PREFERRED_AV_MODE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UPGRADE_SETTINGS() As Boolean
            Get
                Return CType(Me("UPGRADE_SETTINGS"),Boolean)
            End Get
            Set
                Me("UPGRADE_SETTINGS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property PREFERRED_HDMI_RESOLUTION() As Byte
            Get
                Return CType(Me("PREFERRED_HDMI_RESOLUTION"),Byte)
            End Get
            Set
                Me("PREFERRED_HDMI_RESOLUTION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PREFERRED_HDMI_MAXIMIZED() As Boolean
            Get
                Return CType(Me("PREFERRED_HDMI_MAXIMIZED"),Boolean)
            End Get
            Set
                Me("PREFERRED_HDMI_MAXIMIZED") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property PREFERRED_HDMI_SCALINGMODE() As Byte
            Get
                Return CType(Me("PREFERRED_HDMI_SCALINGMODE"),Byte)
            End Get
            Set
                Me("PREFERRED_HDMI_SCALINGMODE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DVD_NOTIFY_NONSEAMLESSCELL() As Boolean
            Get
                Return CType(Me("DVD_NOTIFY_NONSEAMLESSCELL"),Boolean)
            End Get
            Set
                Me("DVD_NOTIFY_NONSEAMLESSCELL") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SMT.Applications.Phoenix.My.MySettings
            Get
                Return Global.SMT.Applications.Phoenix.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
